# Generated by Django 4.2.4 on 2023-12-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_order_published_order_price_order_programmer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='taken',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
