# Generated by Django 4.2.4 on 2024-03-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
    ]
