# Generated by Django 4.2.4 on 2023-09-15 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 15, 9, 29, 32, 293403, tzinfo=datetime.timezone.utc)),
        ),
    ]
